#include <exception>

void Throw() {
  //
  throw std::exception();
}
